name = "XLEs"
uuid = "aa8469b8-5d1d-4774-97a7-e6cb72aa2eec"
authors = ["Kadir Gunel"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"

[compat]
Distances = "0.10"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
